multipart:
  maxFileSize: 20MB
  maxRequestSize: 20MB
spring:
    datasource:
        url: "jdbc:postgresql://127.0.0.1:5432/"
        schema: public
        driverClassName: org.postgresql.Driver
        platform: postgresql
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
        show-sql: true
logging:
    level: INFO  
# TODO
#system.translations = stylesheet/less=stylesheet,less/main.less=less_compiled/main.min.css,less.min.js=dummy.js
