multipart:
  maxFileSize: 20MB
  maxRequestSize: 20MB
spring:
    datasource:
        url: "jdbc:postgresql://127.0.0.1:5432/"
        schema: public
        driverClassName: org.postgresql.Driver
        platform: postgresql
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
        show-sql: true
server:
    port: 8086        
logging:
    level: INFO  
eureka:
    client:
        serviceUrl:
            defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
# TODO
#system.translations = stylesheet/less=stylesheet,less/main.less=less_compiled/main.min.css,less.min.js=dummy.js
